name: Cypress base image upload

on: 
  push:
    branches: main
    paths: Dockerfile
  workflow_dispatch:
    
jobs:
  update:
    env:
      USERNAME: ${{ secrets.QUAY_USER }}
      TOKEN: ${{ secrets.QUAY_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Checkout hac-dev
        uses: actions/checkout@v3
        with:
          repository: openshift/hac-dev
          path: hac-dev
          fetch-depth: 0
      - name: Base image upload
        run: |
          podman build -f Dockerfile -t quay.io/hacdev/hac-tests:base
          podman login -u="$USERNAME" -p="$TOKEN" quay.io
          podman push quay.io/hacdev/hac-tests:base
      - name: Update runner image
        run: |
          cd hac-dev/integration-tests
          podman build -f Dockerfile -t quay.io/hacdev/hac-tests:next
          podman login -u="$USERNAME" -p="$TOKEN" quay.io
          podman push quay.io/hacdev/hac-tests:next
      
