name: Cypress runner image upload

on:
  workflow_dispatch:
# schedule:
#  - cron: "*/30 * * * *"
    
jobs:
  changes:
    name: Check for changes from last run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout hac-dev
        uses: actions/checkout@v3
        with:
          repository: openshift/hac-dev
          path: hac-dev
          fetch-depth: 0
      - name: Check the changes to tests since last run
        id: changes
        run: |
          set +e
          cd hac-dev
          git log -n 4
          git diff --name-only "@{30 minutes ago}" | grep integration-tests
          updates=$?
          if [ $updates -ne 0 ]; then
            echo "No changes"
            echo "push_image=false" >> $GITHUB_OUTPUT
          else 
            echo "Changes detected"
            echo "push_image=true" >> $GITHUB_OUTPUT
          fi
      - name: Build and push image
        if: steps.changes.outputs.push_image == 'true'
        env:
          USERNAME: ${{ secrets.QUAY_USER }}
          TOKEN: ${{ secrets.QUAY_TOKEN }}
        run: |
          cd hac-dev/integration-tests
          podman build -f Dockerfile -t quay.io/hacdev/hac-tests:next
          podman login -u="$USERNAME" -p="$TOKEN" quay.io
          podman push quay.io/hacdev/hac-tests:next
