name: Cypress runner image upload

on:
  schedule:
   - cron: "*/30 * * * *"
  workflow_dispatch:
    
jobs:
  changes:
    name: Cypress runner image update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout hac-dev
        uses: actions/checkout@v3
        with:
          repository: openshift/hac-dev
          path: hac-dev
          fetch-depth: 0
      - name: Check the changes to tests since last run
        id: changes
        run: |
          cd hac-dev
          podman pull quay.io/hacdev/hac-tests:next
          
          builddate=$(podman inspect quay.io/hacdev/hac-tests:next --format "{{.Created}}" | sed -r 's/\sUTC//')
          changedate=$(TZ=UTC git log --date=iso-local --format=%cd -n 1 --first-parent -- integration-tests/)
          
          echo "last image build date: $builddate"
          echo "last change date: $changedate"
          
          buildstamp=$(date -d "$builddate" +%s)
          changestamp=$(date -d "$changedate" +%s)
          
          if [ $changestamp -lt $buildstamp ]; then
            echo "No changes"
            echo "push_image=false" >> $GITHUB_OUTPUT
          else 
            echo "Changes detected"
            echo "push_image=true" >> $GITHUB_OUTPUT
          fi
      - name: Build and push image
        if: steps.changes.outputs.push_image == 'true'
        env:
          USERNAME: ${{ secrets.QUAY_USER }}
          TOKEN: ${{ secrets.QUAY_TOKEN }}
        run: |
          cd hac-dev/integration-tests
          podman build -f Dockerfile -t quay.io/hacdev/hac-tests:next
          podman login -u="$USERNAME" -p="$TOKEN" quay.io
          podman push quay.io/hacdev/hac-tests:next
