name: Gitops repository cleanup

on:
  schedule:
   - cron: "0 0 * * 0"
  workflow_dispatch:
    
jobs:
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Delete leftover repositories
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -L -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/orgs/redhat-hac-qe/repos?per_page=100" | jq -r '.[] | .name' | grep -E 'test-app-|devfile-sample-go-basic-' >> repos
            
          while read repo; do curl -L -X DELETE -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/redhat-hac-qe/$repo"; done < repos
         
